services:
  - type: web
    name: solpi
    env: static
    buildCommand: npm install -g serve
    startCommand: serve -s .
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 